name: CICD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy_in_dev:
    runs-on: [ubuntu-latest]
    steps:
      - name: Build codebase
        run: echo "Building the code...."
      - name: Deploy artifacts....
        run: echo "Deploying the artifacts"
  
  deploy_in_qa:
    needs: [build_and_deploy_in_dev]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: QA Deploy
        run: echo "Deploying in QA"
  
  validate_for_prod_deployment:
    needs: [deploy_in_qa]
    runs-on: [ ubuntu-latest ]
    env:
      CURRENT_DAY: "$(date +%u)"
    steps:
      - name: "Set CURRENT_DAY variable"
        id: set_current_day
        run: echo "CURRENT_DAY=$(date +%u)" >> $GITHUB_ENV
      
      - name: Validate for Production Deploy
        run: |
          if [ "${{ vars.DEFAULT_FLOW }}" = "ENABLED" ]; then
            echo "Default flow is enabled. Hence proceeding with deployment to Production."
            exit 0
          fi
          if [[ "${{ vars.DEFAULT_FLOW }}" = "DISABLED"  &&  "$CURRENT_DAY" < "${{ vars.PAUSE_DAY_OF_THE_WEEK }}" ]]; then
            echo "Current day is neither Friday nor Weekend. Hence proceeding with deployment to Production."
            exit 0
          else
            echo "Current day is either Friday or Weekend. Hence Failing the production deployment"
            exit 1
          fi

  deploy_in_prod:
    needs: [deploy_in_qa, validate_for_prod_deployment]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Prod deploy
        run: echo "Deploying in QA"
