name: CICD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy_in_dev:
    runs-on: [ubuntu-latest]
    steps:
      - name: Build codebase
        run: echo "Building the code..."
      - name: Deploy artifacts....
        run: echo "Deploying the artifacts"
        
  deploy_in_qa:
    needs: [build_and_deploy_in_dev]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: QA Deploy
        run: echo "Deploying in QA"
  
  validate_for_prod_deployment:
    needs: [deploy_in_qa]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: "Set CURRENT_DAY variable"
        id: set_current_day
        run: echo "CURRENT_DAY=$(date +%u)" >> $GITHUB_ENV
        
      - name: Validate for Production Deploy
        run: |
          if ${{ (vars.DEFAULT_FLOW == 'ENABLED') }} then
            echo "Failing the Stage as Production deployment is not allowed"
            exit 1
          else
            echo "Proceeding to Deployment..."
          fi
          echo "current day is $CURRENT_DAY"

  deploy_in_prod:
    needs: [deploy_in_qa, validate_for_prod_deployment]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Prod deploy
        run: echo "Deploying in QA"
